// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// ChannelGovernanceRepoMock is an autogenerated mock type for the ChannelGovernanceRepo type
type ChannelGovernanceRepoMock struct {
	mock.Mock
}

type ChannelGovernanceRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelGovernanceRepoMock) EXPECT() *ChannelGovernanceRepoMock_Expecter {
	return &ChannelGovernanceRepoMock_Expecter{mock: &_m.Mock}
}

// AddManager provides a mock function with given fields: ctx, channelID, userID, addedBy
func (_m *ChannelGovernanceRepoMock) AddManager(ctx context.Context, channelID string, userID string, addedBy string) error {
	ret := _m.Called(ctx, channelID, userID, addedBy)

	if len(ret) == 0 {
		panic("no return value specified for AddManager")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, channelID, userID, addedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_AddManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddManager'
type ChannelGovernanceRepoMock_AddManager_Call struct {
	*mock.Call
}

// AddManager is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - userID string
//   - addedBy string
func (_e *ChannelGovernanceRepoMock_Expecter) AddManager(ctx interface{}, channelID interface{}, userID interface{}, addedBy interface{}) *ChannelGovernanceRepoMock_AddManager_Call {
	return &ChannelGovernanceRepoMock_AddManager_Call{Call: _e.mock.On("AddManager", ctx, channelID, userID, addedBy)}
}

func (_c *ChannelGovernanceRepoMock_AddManager_Call) Run(run func(ctx context.Context, channelID string, userID string, addedBy string)) *ChannelGovernanceRepoMock_AddManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_AddManager_Call) Return(_a0 error) *ChannelGovernanceRepoMock_AddManager_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_AddManager_Call) RunAndReturn(run func(context.Context, string, string, string) error) *ChannelGovernanceRepoMock_AddManager_Call {
	_c.Call.Return(run)
	return _c
}

// IsManager provides a mock function with given fields: ctx, channelID, userID
func (_m *ChannelGovernanceRepoMock) IsManager(ctx context.Context, channelID string, userID string) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsManager")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelGovernanceRepoMock_IsManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsManager'
type ChannelGovernanceRepoMock_IsManager_Call struct {
	*mock.Call
}

// IsManager is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - userID string
func (_e *ChannelGovernanceRepoMock_Expecter) IsManager(ctx interface{}, channelID interface{}, userID interface{}) *ChannelGovernanceRepoMock_IsManager_Call {
	return &ChannelGovernanceRepoMock_IsManager_Call{Call: _e.mock.On("IsManager", ctx, channelID, userID)}
}

func (_c *ChannelGovernanceRepoMock_IsManager_Call) Run(run func(ctx context.Context, channelID string, userID string)) *ChannelGovernanceRepoMock_IsManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_IsManager_Call) Return(_a0 bool, _a1 error) *ChannelGovernanceRepoMock_IsManager_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelGovernanceRepoMock_IsManager_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ChannelGovernanceRepoMock_IsManager_Call {
	_c.Call.Return(run)
	return _c
}

// ListManagers provides a mock function with given fields: ctx, channelID
func (_m *ChannelGovernanceRepoMock) ListManagers(ctx context.Context, channelID string) ([]string, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListManagers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelGovernanceRepoMock_ListManagers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManagers'
type ChannelGovernanceRepoMock_ListManagers_Call struct {
	*mock.Call
}

// ListManagers is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
func (_e *ChannelGovernanceRepoMock_Expecter) ListManagers(ctx interface{}, channelID interface{}) *ChannelGovernanceRepoMock_ListManagers_Call {
	return &ChannelGovernanceRepoMock_ListManagers_Call{Call: _e.mock.On("ListManagers", ctx, channelID)}
}

func (_c *ChannelGovernanceRepoMock_ListManagers_Call) Run(run func(ctx context.Context, channelID string)) *ChannelGovernanceRepoMock_ListManagers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_ListManagers_Call) Return(_a0 []string, _a1 error) *ChannelGovernanceRepoMock_ListManagers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelGovernanceRepoMock_ListManagers_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *ChannelGovernanceRepoMock_ListManagers_Call {
	_c.Call.Return(run)
	return _c
}

// ListPins provides a mock function with given fields: ctx, channelID
func (_m *ChannelGovernanceRepoMock) ListPins(ctx context.Context, channelID string) ([]string, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListPins")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelGovernanceRepoMock_ListPins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPins'
type ChannelGovernanceRepoMock_ListPins_Call struct {
	*mock.Call
}

// ListPins is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
func (_e *ChannelGovernanceRepoMock_Expecter) ListPins(ctx interface{}, channelID interface{}) *ChannelGovernanceRepoMock_ListPins_Call {
	return &ChannelGovernanceRepoMock_ListPins_Call{Call: _e.mock.On("ListPins", ctx, channelID)}
}

func (_c *ChannelGovernanceRepoMock_ListPins_Call) Run(run func(ctx context.Context, channelID string)) *ChannelGovernanceRepoMock_ListPins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_ListPins_Call) Return(_a0 []string, _a1 error) *ChannelGovernanceRepoMock_ListPins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelGovernanceRepoMock_ListPins_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *ChannelGovernanceRepoMock_ListPins_Call {
	_c.Call.Return(run)
	return _c
}

// PatchChannel provides a mock function with given fields: ctx, channelID, fields
func (_m *ChannelGovernanceRepoMock) PatchChannel(ctx context.Context, channelID string, fields repo.PatchChannelFields) error {
	ret := _m.Called(ctx, channelID, fields)

	if len(ret) == 0 {
		panic("no return value specified for PatchChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repo.PatchChannelFields) error); ok {
		r0 = rf(ctx, channelID, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_PatchChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchChannel'
type ChannelGovernanceRepoMock_PatchChannel_Call struct {
	*mock.Call
}

// PatchChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - fields repo.PatchChannelFields
func (_e *ChannelGovernanceRepoMock_Expecter) PatchChannel(ctx interface{}, channelID interface{}, fields interface{}) *ChannelGovernanceRepoMock_PatchChannel_Call {
	return &ChannelGovernanceRepoMock_PatchChannel_Call{Call: _e.mock.On("PatchChannel", ctx, channelID, fields)}
}

func (_c *ChannelGovernanceRepoMock_PatchChannel_Call) Run(run func(ctx context.Context, channelID string, fields repo.PatchChannelFields)) *ChannelGovernanceRepoMock_PatchChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(repo.PatchChannelFields))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_PatchChannel_Call) Return(_a0 error) *ChannelGovernanceRepoMock_PatchChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_PatchChannel_Call) RunAndReturn(run func(context.Context, string, repo.PatchChannelFields) error) *ChannelGovernanceRepoMock_PatchChannel_Call {
	_c.Call.Return(run)
	return _c
}

// PinMessage provides a mock function with given fields: ctx, channelID, msgID, pinnedBy
func (_m *ChannelGovernanceRepoMock) PinMessage(ctx context.Context, channelID string, msgID string, pinnedBy string) error {
	ret := _m.Called(ctx, channelID, msgID, pinnedBy)

	if len(ret) == 0 {
		panic("no return value specified for PinMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, channelID, msgID, pinnedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_PinMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PinMessage'
type ChannelGovernanceRepoMock_PinMessage_Call struct {
	*mock.Call
}

// PinMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - msgID string
//   - pinnedBy string
func (_e *ChannelGovernanceRepoMock_Expecter) PinMessage(ctx interface{}, channelID interface{}, msgID interface{}, pinnedBy interface{}) *ChannelGovernanceRepoMock_PinMessage_Call {
	return &ChannelGovernanceRepoMock_PinMessage_Call{Call: _e.mock.On("PinMessage", ctx, channelID, msgID, pinnedBy)}
}

func (_c *ChannelGovernanceRepoMock_PinMessage_Call) Run(run func(ctx context.Context, channelID string, msgID string, pinnedBy string)) *ChannelGovernanceRepoMock_PinMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_PinMessage_Call) Return(_a0 error) *ChannelGovernanceRepoMock_PinMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_PinMessage_Call) RunAndReturn(run func(context.Context, string, string, string) error) *ChannelGovernanceRepoMock_PinMessage_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveManager provides a mock function with given fields: ctx, channelID, userID
func (_m *ChannelGovernanceRepoMock) RemoveManager(ctx context.Context, channelID string, userID string) error {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveManager")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_RemoveManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveManager'
type ChannelGovernanceRepoMock_RemoveManager_Call struct {
	*mock.Call
}

// RemoveManager is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - userID string
func (_e *ChannelGovernanceRepoMock_Expecter) RemoveManager(ctx interface{}, channelID interface{}, userID interface{}) *ChannelGovernanceRepoMock_RemoveManager_Call {
	return &ChannelGovernanceRepoMock_RemoveManager_Call{Call: _e.mock.On("RemoveManager", ctx, channelID, userID)}
}

func (_c *ChannelGovernanceRepoMock_RemoveManager_Call) Run(run func(ctx context.Context, channelID string, userID string)) *ChannelGovernanceRepoMock_RemoveManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_RemoveManager_Call) Return(_a0 error) *ChannelGovernanceRepoMock_RemoveManager_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_RemoveManager_Call) RunAndReturn(run func(context.Context, string, string) error) *ChannelGovernanceRepoMock_RemoveManager_Call {
	_c.Call.Return(run)
	return _c
}

// UnpinMessage provides a mock function with given fields: ctx, channelID, msgID
func (_m *ChannelGovernanceRepoMock) UnpinMessage(ctx context.Context, channelID string, msgID string) error {
	ret := _m.Called(ctx, channelID, msgID)

	if len(ret) == 0 {
		panic("no return value specified for UnpinMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, channelID, msgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_UnpinMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpinMessage'
type ChannelGovernanceRepoMock_UnpinMessage_Call struct {
	*mock.Call
}

// UnpinMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - msgID string
func (_e *ChannelGovernanceRepoMock_Expecter) UnpinMessage(ctx interface{}, channelID interface{}, msgID interface{}) *ChannelGovernanceRepoMock_UnpinMessage_Call {
	return &ChannelGovernanceRepoMock_UnpinMessage_Call{Call: _e.mock.On("UnpinMessage", ctx, channelID, msgID)}
}

func (_c *ChannelGovernanceRepoMock_UnpinMessage_Call) Run(run func(ctx context.Context, channelID string, msgID string)) *ChannelGovernanceRepoMock_UnpinMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_UnpinMessage_Call) Return(_a0 error) *ChannelGovernanceRepoMock_UnpinMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_UnpinMessage_Call) RunAndReturn(run func(context.Context, string, string) error) *ChannelGovernanceRepoMock_UnpinMessage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberIsTop provides a mock function with given fields: ctx, channelID, userID, isTop
func (_m *ChannelGovernanceRepoMock) UpdateMemberIsTop(ctx context.Context, channelID string, userID string, isTop bool) error {
	ret := _m.Called(ctx, channelID, userID, isTop)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberIsTop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, channelID, userID, isTop)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_UpdateMemberIsTop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberIsTop'
type ChannelGovernanceRepoMock_UpdateMemberIsTop_Call struct {
	*mock.Call
}

// UpdateMemberIsTop is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - userID string
//   - isTop bool
func (_e *ChannelGovernanceRepoMock_Expecter) UpdateMemberIsTop(ctx interface{}, channelID interface{}, userID interface{}, isTop interface{}) *ChannelGovernanceRepoMock_UpdateMemberIsTop_Call {
	return &ChannelGovernanceRepoMock_UpdateMemberIsTop_Call{Call: _e.mock.On("UpdateMemberIsTop", ctx, channelID, userID, isTop)}
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberIsTop_Call) Run(run func(ctx context.Context, channelID string, userID string, isTop bool)) *ChannelGovernanceRepoMock_UpdateMemberIsTop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberIsTop_Call) Return(_a0 error) *ChannelGovernanceRepoMock_UpdateMemberIsTop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberIsTop_Call) RunAndReturn(run func(context.Context, string, string, bool) error) *ChannelGovernanceRepoMock_UpdateMemberIsTop_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberNotifyPref provides a mock function with given fields: ctx, channelID, userID, pref
func (_m *ChannelGovernanceRepoMock) UpdateMemberNotifyPref(ctx context.Context, channelID string, userID string, pref int16) error {
	ret := _m.Called(ctx, channelID, userID, pref)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberNotifyPref")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int16) error); ok {
		r0 = rf(ctx, channelID, userID, pref)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberNotifyPref'
type ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call struct {
	*mock.Call
}

// UpdateMemberNotifyPref is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - userID string
//   - pref int16
func (_e *ChannelGovernanceRepoMock_Expecter) UpdateMemberNotifyPref(ctx interface{}, channelID interface{}, userID interface{}, pref interface{}) *ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call {
	return &ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call{Call: _e.mock.On("UpdateMemberNotifyPref", ctx, channelID, userID, pref)}
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call) Run(run func(ctx context.Context, channelID string, userID string, pref int16)) *ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int16))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call) Return(_a0 error) *ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call) RunAndReturn(run func(context.Context, string, string, int16) error) *ChannelGovernanceRepoMock_UpdateMemberNotifyPref_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, channelID, userID, role
func (_m *ChannelGovernanceRepoMock) UpdateMemberRole(ctx context.Context, channelID string, userID string, role int16) error {
	ret := _m.Called(ctx, channelID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int16) error); ok {
		r0 = rf(ctx, channelID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelGovernanceRepoMock_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type ChannelGovernanceRepoMock_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - userID string
//   - role int16
func (_e *ChannelGovernanceRepoMock_Expecter) UpdateMemberRole(ctx interface{}, channelID interface{}, userID interface{}, role interface{}) *ChannelGovernanceRepoMock_UpdateMemberRole_Call {
	return &ChannelGovernanceRepoMock_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, channelID, userID, role)}
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberRole_Call) Run(run func(ctx context.Context, channelID string, userID string, role int16)) *ChannelGovernanceRepoMock_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int16))
	})
	return _c
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberRole_Call) Return(_a0 error) *ChannelGovernanceRepoMock_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelGovernanceRepoMock_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, string, string, int16) error) *ChannelGovernanceRepoMock_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelGovernanceRepoMock creates a new instance of ChannelGovernanceRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelGovernanceRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelGovernanceRepoMock {
	mock := &ChannelGovernanceRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
