// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// ChannelRepoMock is an autogenerated mock type for the ChannelRepo type
type ChannelRepoMock struct {
	mock.Mock
}

type ChannelRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelRepoMock) EXPECT() *ChannelRepoMock_Expecter {
	return &ChannelRepoMock_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, channelID, userID, role
func (_m *ChannelRepoMock) AddMember(ctx context.Context, channelID int64, userID int64, role int16) error {
	ret := _m.Called(ctx, channelID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int16) error); ok {
		r0 = rf(ctx, channelID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelRepoMock_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type ChannelRepoMock_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - userID int64
//   - role int16
func (_e *ChannelRepoMock_Expecter) AddMember(ctx interface{}, channelID interface{}, userID interface{}, role interface{}) *ChannelRepoMock_AddMember_Call {
	return &ChannelRepoMock_AddMember_Call{Call: _e.mock.On("AddMember", ctx, channelID, userID, role)}
}

func (_c *ChannelRepoMock_AddMember_Call) Run(run func(ctx context.Context, channelID int64, userID int64, role int16)) *ChannelRepoMock_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int16))
	})
	return _c
}

func (_c *ChannelRepoMock_AddMember_Call) Return(_a0 error) *ChannelRepoMock_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelRepoMock_AddMember_Call) RunAndReturn(run func(context.Context, int64, int64, int16) error) *ChannelRepoMock_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, ch
func (_m *ChannelRepoMock) Create(ctx context.Context, ch *repo.Channel) error {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.Channel) error); ok {
		r0 = rf(ctx, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelRepoMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ChannelRepoMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ch *repo.Channel
func (_e *ChannelRepoMock_Expecter) Create(ctx interface{}, ch interface{}) *ChannelRepoMock_Create_Call {
	return &ChannelRepoMock_Create_Call{Call: _e.mock.On("Create", ctx, ch)}
}

func (_c *ChannelRepoMock_Create_Call) Run(run func(ctx context.Context, ch *repo.Channel)) *ChannelRepoMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repo.Channel))
	})
	return _c
}

func (_c *ChannelRepoMock_Create_Call) Return(_a0 error) *ChannelRepoMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelRepoMock_Create_Call) RunAndReturn(run func(context.Context, *repo.Channel) error) *ChannelRepoMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindDM provides a mock function with given fields: ctx, userA, userB
func (_m *ChannelRepoMock) FindDM(ctx context.Context, userA int64, userB int64) (*repo.Channel, error) {
	ret := _m.Called(ctx, userA, userB)

	if len(ret) == 0 {
		panic("no return value specified for FindDM")
	}

	var r0 *repo.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*repo.Channel, error)); ok {
		return rf(ctx, userA, userB)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *repo.Channel); ok {
		r0 = rf(ctx, userA, userB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userA, userB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_FindDM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDM'
type ChannelRepoMock_FindDM_Call struct {
	*mock.Call
}

// FindDM is a helper method to define mock.On call
//   - ctx context.Context
//   - userA int64
//   - userB int64
func (_e *ChannelRepoMock_Expecter) FindDM(ctx interface{}, userA interface{}, userB interface{}) *ChannelRepoMock_FindDM_Call {
	return &ChannelRepoMock_FindDM_Call{Call: _e.mock.On("FindDM", ctx, userA, userB)}
}

func (_c *ChannelRepoMock_FindDM_Call) Run(run func(ctx context.Context, userA int64, userB int64)) *ChannelRepoMock_FindDM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_FindDM_Call) Return(_a0 *repo.Channel, _a1 error) *ChannelRepoMock_FindDM_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_FindDM_Call) RunAndReturn(run func(context.Context, int64, int64) (*repo.Channel, error)) *ChannelRepoMock_FindDM_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ChannelRepoMock) GetByID(ctx context.Context, id int64) (*repo.Channel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *repo.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repo.Channel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repo.Channel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ChannelRepoMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ChannelRepoMock_Expecter) GetByID(ctx interface{}, id interface{}) *ChannelRepoMock_GetByID_Call {
	return &ChannelRepoMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ChannelRepoMock_GetByID_Call) Run(run func(ctx context.Context, id int64)) *ChannelRepoMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_GetByID_Call) Return(_a0 *repo.Channel, _a1 error) *ChannelRepoMock_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*repo.Channel, error)) *ChannelRepoMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, channelID, userID
func (_m *ChannelRepoMock) GetMember(ctx context.Context, channelID int64, userID int64) (*repo.ChannelMember, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 *repo.ChannelMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*repo.ChannelMember, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *repo.ChannelMember); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.ChannelMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type ChannelRepoMock_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - userID int64
func (_e *ChannelRepoMock_Expecter) GetMember(ctx interface{}, channelID interface{}, userID interface{}) *ChannelRepoMock_GetMember_Call {
	return &ChannelRepoMock_GetMember_Call{Call: _e.mock.On("GetMember", ctx, channelID, userID)}
}

func (_c *ChannelRepoMock_GetMember_Call) Run(run func(ctx context.Context, channelID int64, userID int64)) *ChannelRepoMock_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_GetMember_Call) Return(_a0 *repo.ChannelMember, _a1 error) *ChannelRepoMock_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_GetMember_Call) RunAndReturn(run func(context.Context, int64, int64) (*repo.ChannelMember, error)) *ChannelRepoMock_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberChannelSeqs provides a mock function with given fields: ctx, userID
func (_m *ChannelRepoMock) GetMemberChannelSeqs(ctx context.Context, userID int64) (map[int64]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberChannelSeqs")
	}

	var r0 map[int64]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[int64]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[int64]int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_GetMemberChannelSeqs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberChannelSeqs'
type ChannelRepoMock_GetMemberChannelSeqs_Call struct {
	*mock.Call
}

// GetMemberChannelSeqs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ChannelRepoMock_Expecter) GetMemberChannelSeqs(ctx interface{}, userID interface{}) *ChannelRepoMock_GetMemberChannelSeqs_Call {
	return &ChannelRepoMock_GetMemberChannelSeqs_Call{Call: _e.mock.On("GetMemberChannelSeqs", ctx, userID)}
}

func (_c *ChannelRepoMock_GetMemberChannelSeqs_Call) Run(run func(ctx context.Context, userID int64)) *ChannelRepoMock_GetMemberChannelSeqs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_GetMemberChannelSeqs_Call) Return(_a0 map[int64]int64, _a1 error) *ChannelRepoMock_GetMemberChannelSeqs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_GetMemberChannelSeqs_Call) RunAndReturn(run func(context.Context, int64) (map[int64]int64, error)) *ChannelRepoMock_GetMemberChannelSeqs_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementPhantomCount provides a mock function with given fields: ctx, tx, channelID, excludeUserIDs
func (_m *ChannelRepoMock) IncrementPhantomCount(ctx context.Context, tx *gorm.DB, channelID int64, excludeUserIDs []int64) error {
	ret := _m.Called(ctx, tx, channelID, excludeUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for IncrementPhantomCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, []int64) error); ok {
		r0 = rf(ctx, tx, channelID, excludeUserIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelRepoMock_IncrementPhantomCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementPhantomCount'
type ChannelRepoMock_IncrementPhantomCount_Call struct {
	*mock.Call
}

// IncrementPhantomCount is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - channelID int64
//   - excludeUserIDs []int64
func (_e *ChannelRepoMock_Expecter) IncrementPhantomCount(ctx interface{}, tx interface{}, channelID interface{}, excludeUserIDs interface{}) *ChannelRepoMock_IncrementPhantomCount_Call {
	return &ChannelRepoMock_IncrementPhantomCount_Call{Call: _e.mock.On("IncrementPhantomCount", ctx, tx, channelID, excludeUserIDs)}
}

func (_c *ChannelRepoMock_IncrementPhantomCount_Call) Run(run func(ctx context.Context, tx *gorm.DB, channelID int64, excludeUserIDs []int64)) *ChannelRepoMock_IncrementPhantomCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(int64), args[3].([]int64))
	})
	return _c
}

func (_c *ChannelRepoMock_IncrementPhantomCount_Call) Return(_a0 error) *ChannelRepoMock_IncrementPhantomCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelRepoMock_IncrementPhantomCount_Call) RunAndReturn(run func(context.Context, *gorm.DB, int64, []int64) error) *ChannelRepoMock_IncrementPhantomCount_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementSeq provides a mock function with given fields: ctx, tx, channelID
func (_m *ChannelRepoMock) IncrementSeq(ctx context.Context, tx *gorm.DB, channelID int64) (int64, error) {
	ret := _m.Called(ctx, tx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementSeq")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) (int64, error)); ok {
		return rf(ctx, tx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) int64); ok {
		r0 = rf(ctx, tx, channelID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64) error); ok {
		r1 = rf(ctx, tx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_IncrementSeq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementSeq'
type ChannelRepoMock_IncrementSeq_Call struct {
	*mock.Call
}

// IncrementSeq is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - channelID int64
func (_e *ChannelRepoMock_Expecter) IncrementSeq(ctx interface{}, tx interface{}, channelID interface{}) *ChannelRepoMock_IncrementSeq_Call {
	return &ChannelRepoMock_IncrementSeq_Call{Call: _e.mock.On("IncrementSeq", ctx, tx, channelID)}
}

func (_c *ChannelRepoMock_IncrementSeq_Call) Run(run func(ctx context.Context, tx *gorm.DB, channelID int64)) *ChannelRepoMock_IncrementSeq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_IncrementSeq_Call) Return(_a0 int64, _a1 error) *ChannelRepoMock_IncrementSeq_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_IncrementSeq_Call) RunAndReturn(run func(context.Context, *gorm.DB, int64) (int64, error)) *ChannelRepoMock_IncrementSeq_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *ChannelRepoMock) ListByUser(ctx context.Context, userID int64) ([]repo.Channel, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []repo.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]repo.Channel, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []repo.Channel); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type ChannelRepoMock_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ChannelRepoMock_Expecter) ListByUser(ctx interface{}, userID interface{}) *ChannelRepoMock_ListByUser_Call {
	return &ChannelRepoMock_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *ChannelRepoMock_ListByUser_Call) Run(run func(ctx context.Context, userID int64)) *ChannelRepoMock_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_ListByUser_Call) Return(_a0 []repo.Channel, _a1 error) *ChannelRepoMock_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_ListByUser_Call) RunAndReturn(run func(context.Context, int64) ([]repo.Channel, error)) *ChannelRepoMock_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserWithPreview provides a mock function with given fields: ctx, userID
func (_m *ChannelRepoMock) ListByUserWithPreview(ctx context.Context, userID int64) ([]repo.ChannelWithPreview, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserWithPreview")
	}

	var r0 []repo.ChannelWithPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]repo.ChannelWithPreview, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []repo.ChannelWithPreview); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.ChannelWithPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_ListByUserWithPreview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserWithPreview'
type ChannelRepoMock_ListByUserWithPreview_Call struct {
	*mock.Call
}

// ListByUserWithPreview is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ChannelRepoMock_Expecter) ListByUserWithPreview(ctx interface{}, userID interface{}) *ChannelRepoMock_ListByUserWithPreview_Call {
	return &ChannelRepoMock_ListByUserWithPreview_Call{Call: _e.mock.On("ListByUserWithPreview", ctx, userID)}
}

func (_c *ChannelRepoMock_ListByUserWithPreview_Call) Run(run func(ctx context.Context, userID int64)) *ChannelRepoMock_ListByUserWithPreview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_ListByUserWithPreview_Call) Return(_a0 []repo.ChannelWithPreview, _a1 error) *ChannelRepoMock_ListByUserWithPreview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_ListByUserWithPreview_Call) RunAndReturn(run func(context.Context, int64) ([]repo.ChannelWithPreview, error)) *ChannelRepoMock_ListByUserWithPreview_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, channelID
func (_m *ChannelRepoMock) ListMembers(ctx context.Context, channelID int64) ([]repo.ChannelMember, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []repo.ChannelMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]repo.ChannelMember, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []repo.ChannelMember); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.ChannelMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelRepoMock_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type ChannelRepoMock_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
func (_e *ChannelRepoMock_Expecter) ListMembers(ctx interface{}, channelID interface{}) *ChannelRepoMock_ListMembers_Call {
	return &ChannelRepoMock_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, channelID)}
}

func (_c *ChannelRepoMock_ListMembers_Call) Run(run func(ctx context.Context, channelID int64)) *ChannelRepoMock_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_ListMembers_Call) Return(_a0 []repo.ChannelMember, _a1 error) *ChannelRepoMock_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelRepoMock_ListMembers_Call) RunAndReturn(run func(context.Context, int64) ([]repo.ChannelMember, error)) *ChannelRepoMock_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, channelID, userID, seq
func (_m *ChannelRepoMock) MarkRead(ctx context.Context, channelID int64, userID int64, seq int64) error {
	ret := _m.Called(ctx, channelID, userID, seq)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) error); ok {
		r0 = rf(ctx, channelID, userID, seq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelRepoMock_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type ChannelRepoMock_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - userID int64
//   - seq int64
func (_e *ChannelRepoMock_Expecter) MarkRead(ctx interface{}, channelID interface{}, userID interface{}, seq interface{}) *ChannelRepoMock_MarkRead_Call {
	return &ChannelRepoMock_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, channelID, userID, seq)}
}

func (_c *ChannelRepoMock_MarkRead_Call) Run(run func(ctx context.Context, channelID int64, userID int64, seq int64)) *ChannelRepoMock_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_MarkRead_Call) Return(_a0 error) *ChannelRepoMock_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelRepoMock_MarkRead_Call) RunAndReturn(run func(context.Context, int64, int64, int64) error) *ChannelRepoMock_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, channelID, userID
func (_m *ChannelRepoMock) RemoveMember(ctx context.Context, channelID int64, userID int64) error {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelRepoMock_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type ChannelRepoMock_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - userID int64
func (_e *ChannelRepoMock_Expecter) RemoveMember(ctx interface{}, channelID interface{}, userID interface{}) *ChannelRepoMock_RemoveMember_Call {
	return &ChannelRepoMock_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, channelID, userID)}
}

func (_c *ChannelRepoMock_RemoveMember_Call) Run(run func(ctx context.Context, channelID int64, userID int64)) *ChannelRepoMock_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ChannelRepoMock_RemoveMember_Call) Return(_a0 error) *ChannelRepoMock_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelRepoMock_RemoveMember_Call) RunAndReturn(run func(context.Context, int64, int64) error) *ChannelRepoMock_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, channelID, name, avatarURL
func (_m *ChannelRepoMock) Update(ctx context.Context, channelID int64, name string, avatarURL string) error {
	ret := _m.Called(ctx, channelID, name, avatarURL)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, channelID, name, avatarURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelRepoMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ChannelRepoMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - name string
//   - avatarURL string
func (_e *ChannelRepoMock_Expecter) Update(ctx interface{}, channelID interface{}, name interface{}, avatarURL interface{}) *ChannelRepoMock_Update_Call {
	return &ChannelRepoMock_Update_Call{Call: _e.mock.On("Update", ctx, channelID, name, avatarURL)}
}

func (_c *ChannelRepoMock_Update_Call) Run(run func(ctx context.Context, channelID int64, name string, avatarURL string)) *ChannelRepoMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ChannelRepoMock_Update_Call) Return(_a0 error) *ChannelRepoMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelRepoMock_Update_Call) RunAndReturn(run func(context.Context, int64, string, string) error) *ChannelRepoMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelRepoMock creates a new instance of ChannelRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelRepoMock {
	mock := &ChannelRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
