// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// ChannelEventRepoMock is an autogenerated mock type for the ChannelEventRepo type
type ChannelEventRepoMock struct {
	mock.Mock
}

type ChannelEventRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelEventRepoMock) EXPECT() *ChannelEventRepoMock_Expecter {
	return &ChannelEventRepoMock_Expecter{mock: &_m.Mock}
}

// AppendEvent provides a mock function with given fields: ctx, tx, event
func (_m *ChannelEventRepoMock) AppendEvent(ctx context.Context, tx *gorm.DB, event *repo.ChannelEvent) error {
	ret := _m.Called(ctx, tx, event)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *repo.ChannelEvent) error); ok {
		r0 = rf(ctx, tx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelEventRepoMock_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type ChannelEventRepoMock_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - event *repo.ChannelEvent
func (_e *ChannelEventRepoMock_Expecter) AppendEvent(ctx interface{}, tx interface{}, event interface{}) *ChannelEventRepoMock_AppendEvent_Call {
	return &ChannelEventRepoMock_AppendEvent_Call{Call: _e.mock.On("AppendEvent", ctx, tx, event)}
}

func (_c *ChannelEventRepoMock_AppendEvent_Call) Run(run func(ctx context.Context, tx *gorm.DB, event *repo.ChannelEvent)) *ChannelEventRepoMock_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(*repo.ChannelEvent))
	})
	return _c
}

func (_c *ChannelEventRepoMock_AppendEvent_Call) Return(_a0 error) *ChannelEventRepoMock_AppendEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelEventRepoMock_AppendEvent_Call) RunAndReturn(run func(context.Context, *gorm.DB, *repo.ChannelEvent) error) *ChannelEventRepoMock_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChannelSequences provides a mock function with given fields: ctx, tx, channelID
func (_m *ChannelEventRepoMock) CreateChannelSequences(ctx context.Context, tx *gorm.DB, channelID string) error {
	ret := _m.Called(ctx, tx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannelSequences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) error); ok {
		r0 = rf(ctx, tx, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelEventRepoMock_CreateChannelSequences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChannelSequences'
type ChannelEventRepoMock_CreateChannelSequences_Call struct {
	*mock.Call
}

// CreateChannelSequences is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - channelID string
func (_e *ChannelEventRepoMock_Expecter) CreateChannelSequences(ctx interface{}, tx interface{}, channelID interface{}) *ChannelEventRepoMock_CreateChannelSequences_Call {
	return &ChannelEventRepoMock_CreateChannelSequences_Call{Call: _e.mock.On("CreateChannelSequences", ctx, tx, channelID)}
}

func (_c *ChannelEventRepoMock_CreateChannelSequences_Call) Run(run func(ctx context.Context, tx *gorm.DB, channelID string)) *ChannelEventRepoMock_CreateChannelSequences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(string))
	})
	return _c
}

func (_c *ChannelEventRepoMock_CreateChannelSequences_Call) Return(_a0 error) *ChannelEventRepoMock_CreateChannelSequences_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelEventRepoMock_CreateChannelSequences_Call) RunAndReturn(run func(context.Context, *gorm.DB, string) error) *ChannelEventRepoMock_CreateChannelSequences_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAfter provides a mock function with given fields: ctx, channelID, afterEventSeq, limit
func (_m *ChannelEventRepoMock) FetchAfter(ctx context.Context, channelID string, afterEventSeq int64, limit int) ([]repo.ChannelEvent, error) {
	ret := _m.Called(ctx, channelID, afterEventSeq, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchAfter")
	}

	var r0 []repo.ChannelEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) ([]repo.ChannelEvent, error)); ok {
		return rf(ctx, channelID, afterEventSeq, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) []repo.ChannelEvent); ok {
		r0 = rf(ctx, channelID, afterEventSeq, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.ChannelEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int) error); ok {
		r1 = rf(ctx, channelID, afterEventSeq, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelEventRepoMock_FetchAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAfter'
type ChannelEventRepoMock_FetchAfter_Call struct {
	*mock.Call
}

// FetchAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - afterEventSeq int64
//   - limit int
func (_e *ChannelEventRepoMock_Expecter) FetchAfter(ctx interface{}, channelID interface{}, afterEventSeq interface{}, limit interface{}) *ChannelEventRepoMock_FetchAfter_Call {
	return &ChannelEventRepoMock_FetchAfter_Call{Call: _e.mock.On("FetchAfter", ctx, channelID, afterEventSeq, limit)}
}

func (_c *ChannelEventRepoMock_FetchAfter_Call) Run(run func(ctx context.Context, channelID string, afterEventSeq int64, limit int)) *ChannelEventRepoMock_FetchAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *ChannelEventRepoMock_FetchAfter_Call) Return(_a0 []repo.ChannelEvent, _a1 error) *ChannelEventRepoMock_FetchAfter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelEventRepoMock_FetchAfter_Call) RunAndReturn(run func(context.Context, string, int64, int) ([]repo.ChannelEvent, error)) *ChannelEventRepoMock_FetchAfter_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberChannelEventSeqs provides a mock function with given fields: ctx, userID
func (_m *ChannelEventRepoMock) GetMemberChannelEventSeqs(ctx context.Context, userID string) (map[string]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberChannelEventSeqs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelEventRepoMock_GetMemberChannelEventSeqs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberChannelEventSeqs'
type ChannelEventRepoMock_GetMemberChannelEventSeqs_Call struct {
	*mock.Call
}

// GetMemberChannelEventSeqs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ChannelEventRepoMock_Expecter) GetMemberChannelEventSeqs(ctx interface{}, userID interface{}) *ChannelEventRepoMock_GetMemberChannelEventSeqs_Call {
	return &ChannelEventRepoMock_GetMemberChannelEventSeqs_Call{Call: _e.mock.On("GetMemberChannelEventSeqs", ctx, userID)}
}

func (_c *ChannelEventRepoMock_GetMemberChannelEventSeqs_Call) Run(run func(ctx context.Context, userID string)) *ChannelEventRepoMock_GetMemberChannelEventSeqs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ChannelEventRepoMock_GetMemberChannelEventSeqs_Call) Return(_a0 map[string]int64, _a1 error) *ChannelEventRepoMock_GetMemberChannelEventSeqs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelEventRepoMock_GetMemberChannelEventSeqs_Call) RunAndReturn(run func(context.Context, string) (map[string]int64, error)) *ChannelEventRepoMock_GetMemberChannelEventSeqs_Call {
	_c.Call.Return(run)
	return _c
}

// NextEventSeq provides a mock function with given fields: ctx, tx, channelID
func (_m *ChannelEventRepoMock) NextEventSeq(ctx context.Context, tx *gorm.DB, channelID string) (int64, error) {
	ret := _m.Called(ctx, tx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for NextEventSeq")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (int64, error)); ok {
		return rf(ctx, tx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) int64); ok {
		r0 = rf(ctx, tx, channelID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelEventRepoMock_NextEventSeq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextEventSeq'
type ChannelEventRepoMock_NextEventSeq_Call struct {
	*mock.Call
}

// NextEventSeq is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - channelID string
func (_e *ChannelEventRepoMock_Expecter) NextEventSeq(ctx interface{}, tx interface{}, channelID interface{}) *ChannelEventRepoMock_NextEventSeq_Call {
	return &ChannelEventRepoMock_NextEventSeq_Call{Call: _e.mock.On("NextEventSeq", ctx, tx, channelID)}
}

func (_c *ChannelEventRepoMock_NextEventSeq_Call) Run(run func(ctx context.Context, tx *gorm.DB, channelID string)) *ChannelEventRepoMock_NextEventSeq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(string))
	})
	return _c
}

func (_c *ChannelEventRepoMock_NextEventSeq_Call) Return(_a0 int64, _a1 error) *ChannelEventRepoMock_NextEventSeq_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelEventRepoMock_NextEventSeq_Call) RunAndReturn(run func(context.Context, *gorm.DB, string) (int64, error)) *ChannelEventRepoMock_NextEventSeq_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelEventRepoMock creates a new instance of ChannelEventRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelEventRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelEventRepoMock {
	mock := &ChannelEventRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
