// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// FavoriteRepoMock is an autogenerated mock type for the FavoriteRepo type
type FavoriteRepoMock struct {
	mock.Mock
}

type FavoriteRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoriteRepoMock) EXPECT() *FavoriteRepoMock_Expecter {
	return &FavoriteRepoMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, userID, messageID
func (_m *FavoriteRepoMock) Add(ctx context.Context, userID int64, messageID int64) error {
	ret := _m.Called(ctx, userID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoriteRepoMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type FavoriteRepoMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - messageID int64
func (_e *FavoriteRepoMock_Expecter) Add(ctx interface{}, userID interface{}, messageID interface{}) *FavoriteRepoMock_Add_Call {
	return &FavoriteRepoMock_Add_Call{Call: _e.mock.On("Add", ctx, userID, messageID)}
}

func (_c *FavoriteRepoMock_Add_Call) Run(run func(ctx context.Context, userID int64, messageID int64)) *FavoriteRepoMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FavoriteRepoMock_Add_Call) Return(_a0 error) *FavoriteRepoMock_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoriteRepoMock_Add_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FavoriteRepoMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *FavoriteRepoMock) List(ctx context.Context, userID int64) ([]repo.FavoriteWithMessage, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repo.FavoriteWithMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]repo.FavoriteWithMessage, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []repo.FavoriteWithMessage); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.FavoriteWithMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoriteRepoMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type FavoriteRepoMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *FavoriteRepoMock_Expecter) List(ctx interface{}, userID interface{}) *FavoriteRepoMock_List_Call {
	return &FavoriteRepoMock_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *FavoriteRepoMock_List_Call) Run(run func(ctx context.Context, userID int64)) *FavoriteRepoMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FavoriteRepoMock_List_Call) Return(_a0 []repo.FavoriteWithMessage, _a1 error) *FavoriteRepoMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoriteRepoMock_List_Call) RunAndReturn(run func(context.Context, int64) ([]repo.FavoriteWithMessage, error)) *FavoriteRepoMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, userID, messageID
func (_m *FavoriteRepoMock) Remove(ctx context.Context, userID int64, messageID int64) error {
	ret := _m.Called(ctx, userID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoriteRepoMock_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type FavoriteRepoMock_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - messageID int64
func (_e *FavoriteRepoMock_Expecter) Remove(ctx interface{}, userID interface{}, messageID interface{}) *FavoriteRepoMock_Remove_Call {
	return &FavoriteRepoMock_Remove_Call{Call: _e.mock.On("Remove", ctx, userID, messageID)}
}

func (_c *FavoriteRepoMock_Remove_Call) Run(run func(ctx context.Context, userID int64, messageID int64)) *FavoriteRepoMock_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FavoriteRepoMock_Remove_Call) Return(_a0 error) *FavoriteRepoMock_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoriteRepoMock_Remove_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FavoriteRepoMock_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewFavoriteRepoMock creates a new instance of FavoriteRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoriteRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoriteRepoMock {
	mock := &FavoriteRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
