// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// FileRepoMock is an autogenerated mock type for the FileRepo type
type FileRepoMock struct {
	mock.Mock
}

type FileRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FileRepoMock) EXPECT() *FileRepoMock_Expecter {
	return &FileRepoMock_Expecter{mock: &_m.Mock}
}

// AttachToMessage provides a mock function with given fields: ctx, messageID, fileID
func (_m *FileRepoMock) AttachToMessage(ctx context.Context, messageID int64, fileID int64) error {
	ret := _m.Called(ctx, messageID, fileID)

	if len(ret) == 0 {
		panic("no return value specified for AttachToMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, messageID, fileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileRepoMock_AttachToMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachToMessage'
type FileRepoMock_AttachToMessage_Call struct {
	*mock.Call
}

// AttachToMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID int64
//   - fileID int64
func (_e *FileRepoMock_Expecter) AttachToMessage(ctx interface{}, messageID interface{}, fileID interface{}) *FileRepoMock_AttachToMessage_Call {
	return &FileRepoMock_AttachToMessage_Call{Call: _e.mock.On("AttachToMessage", ctx, messageID, fileID)}
}

func (_c *FileRepoMock_AttachToMessage_Call) Run(run func(ctx context.Context, messageID int64, fileID int64)) *FileRepoMock_AttachToMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FileRepoMock_AttachToMessage_Call) Return(_a0 error) *FileRepoMock_AttachToMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileRepoMock_AttachToMessage_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FileRepoMock_AttachToMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, f
func (_m *FileRepoMock) Create(ctx context.Context, f *repo.File) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.File) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileRepoMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FileRepoMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - f *repo.File
func (_e *FileRepoMock_Expecter) Create(ctx interface{}, f interface{}) *FileRepoMock_Create_Call {
	return &FileRepoMock_Create_Call{Call: _e.mock.On("Create", ctx, f)}
}

func (_c *FileRepoMock_Create_Call) Run(run func(ctx context.Context, f *repo.File)) *FileRepoMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repo.File))
	})
	return _c
}

func (_c *FileRepoMock_Create_Call) Return(_a0 error) *FileRepoMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileRepoMock_Create_Call) RunAndReturn(run func(context.Context, *repo.File) error) *FileRepoMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *FileRepoMock) GetByID(ctx context.Context, id int64) (*repo.File, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *repo.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repo.File, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repo.File); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepoMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type FileRepoMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *FileRepoMock_Expecter) GetByID(ctx interface{}, id interface{}) *FileRepoMock_GetByID_Call {
	return &FileRepoMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *FileRepoMock_GetByID_Call) Run(run func(ctx context.Context, id int64)) *FileRepoMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FileRepoMock_GetByID_Call) Return(_a0 *repo.File, _a1 error) *FileRepoMock_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepoMock_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*repo.File, error)) *FileRepoMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByMessage provides a mock function with given fields: ctx, messageID
func (_m *FileRepoMock) ListByMessage(ctx context.Context, messageID int64) ([]repo.File, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for ListByMessage")
	}

	var r0 []repo.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]repo.File, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []repo.File); ok {
		r0 = rf(ctx, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepoMock_ListByMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByMessage'
type FileRepoMock_ListByMessage_Call struct {
	*mock.Call
}

// ListByMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID int64
func (_e *FileRepoMock_Expecter) ListByMessage(ctx interface{}, messageID interface{}) *FileRepoMock_ListByMessage_Call {
	return &FileRepoMock_ListByMessage_Call{Call: _e.mock.On("ListByMessage", ctx, messageID)}
}

func (_c *FileRepoMock_ListByMessage_Call) Run(run func(ctx context.Context, messageID int64)) *FileRepoMock_ListByMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FileRepoMock_ListByMessage_Call) Return(_a0 []repo.File, _a1 error) *FileRepoMock_ListByMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepoMock_ListByMessage_Call) RunAndReturn(run func(context.Context, int64) ([]repo.File, error)) *FileRepoMock_ListByMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileRepoMock creates a new instance of FileRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileRepoMock {
	mock := &FileRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
