// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// FriendshipRepoMock is an autogenerated mock type for the FriendshipRepo type
type FriendshipRepoMock struct {
	mock.Mock
}

type FriendshipRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendshipRepoMock) EXPECT() *FriendshipRepoMock_Expecter {
	return &FriendshipRepoMock_Expecter{mock: &_m.Mock}
}

// AcceptRequest provides a mock function with given fields: ctx, friendshipID, userID
func (_m *FriendshipRepoMock) AcceptRequest(ctx context.Context, friendshipID int64, userID int64) error {
	ret := _m.Called(ctx, friendshipID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, friendshipID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendshipRepoMock_AcceptRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptRequest'
type FriendshipRepoMock_AcceptRequest_Call struct {
	*mock.Call
}

// AcceptRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - friendshipID int64
//   - userID int64
func (_e *FriendshipRepoMock_Expecter) AcceptRequest(ctx interface{}, friendshipID interface{}, userID interface{}) *FriendshipRepoMock_AcceptRequest_Call {
	return &FriendshipRepoMock_AcceptRequest_Call{Call: _e.mock.On("AcceptRequest", ctx, friendshipID, userID)}
}

func (_c *FriendshipRepoMock_AcceptRequest_Call) Run(run func(ctx context.Context, friendshipID int64, userID int64)) *FriendshipRepoMock_AcceptRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendshipRepoMock_AcceptRequest_Call) Return(_a0 error) *FriendshipRepoMock_AcceptRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FriendshipRepoMock_AcceptRequest_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FriendshipRepoMock_AcceptRequest_Call {
	_c.Call.Return(run)
	return _c
}

// BlockUser provides a mock function with given fields: ctx, blockerID, blockedID
func (_m *FriendshipRepoMock) BlockUser(ctx context.Context, blockerID int64, blockedID int64) error {
	ret := _m.Called(ctx, blockerID, blockedID)

	if len(ret) == 0 {
		panic("no return value specified for BlockUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, blockerID, blockedID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendshipRepoMock_BlockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUser'
type FriendshipRepoMock_BlockUser_Call struct {
	*mock.Call
}

// BlockUser is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerID int64
//   - blockedID int64
func (_e *FriendshipRepoMock_Expecter) BlockUser(ctx interface{}, blockerID interface{}, blockedID interface{}) *FriendshipRepoMock_BlockUser_Call {
	return &FriendshipRepoMock_BlockUser_Call{Call: _e.mock.On("BlockUser", ctx, blockerID, blockedID)}
}

func (_c *FriendshipRepoMock_BlockUser_Call) Run(run func(ctx context.Context, blockerID int64, blockedID int64)) *FriendshipRepoMock_BlockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendshipRepoMock_BlockUser_Call) Return(_a0 error) *FriendshipRepoMock_BlockUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FriendshipRepoMock_BlockUser_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FriendshipRepoMock_BlockUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetFriendship provides a mock function with given fields: ctx, userA, userB
func (_m *FriendshipRepoMock) GetFriendship(ctx context.Context, userA int64, userB int64) (*repo.Friendship, error) {
	ret := _m.Called(ctx, userA, userB)

	if len(ret) == 0 {
		panic("no return value specified for GetFriendship")
	}

	var r0 *repo.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*repo.Friendship, error)); ok {
		return rf(ctx, userA, userB)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *repo.Friendship); ok {
		r0 = rf(ctx, userA, userB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userA, userB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendshipRepoMock_GetFriendship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriendship'
type FriendshipRepoMock_GetFriendship_Call struct {
	*mock.Call
}

// GetFriendship is a helper method to define mock.On call
//   - ctx context.Context
//   - userA int64
//   - userB int64
func (_e *FriendshipRepoMock_Expecter) GetFriendship(ctx interface{}, userA interface{}, userB interface{}) *FriendshipRepoMock_GetFriendship_Call {
	return &FriendshipRepoMock_GetFriendship_Call{Call: _e.mock.On("GetFriendship", ctx, userA, userB)}
}

func (_c *FriendshipRepoMock_GetFriendship_Call) Run(run func(ctx context.Context, userA int64, userB int64)) *FriendshipRepoMock_GetFriendship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendshipRepoMock_GetFriendship_Call) Return(_a0 *repo.Friendship, _a1 error) *FriendshipRepoMock_GetFriendship_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendshipRepoMock_GetFriendship_Call) RunAndReturn(run func(context.Context, int64, int64) (*repo.Friendship, error)) *FriendshipRepoMock_GetFriendship_Call {
	_c.Call.Return(run)
	return _c
}

// ListFriends provides a mock function with given fields: ctx, userID
func (_m *FriendshipRepoMock) ListFriends(ctx context.Context, userID int64) ([]repo.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListFriends")
	}

	var r0 []repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]repo.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []repo.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendshipRepoMock_ListFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFriends'
type FriendshipRepoMock_ListFriends_Call struct {
	*mock.Call
}

// ListFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *FriendshipRepoMock_Expecter) ListFriends(ctx interface{}, userID interface{}) *FriendshipRepoMock_ListFriends_Call {
	return &FriendshipRepoMock_ListFriends_Call{Call: _e.mock.On("ListFriends", ctx, userID)}
}

func (_c *FriendshipRepoMock_ListFriends_Call) Run(run func(ctx context.Context, userID int64)) *FriendshipRepoMock_ListFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FriendshipRepoMock_ListFriends_Call) Return(_a0 []repo.User, _a1 error) *FriendshipRepoMock_ListFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendshipRepoMock_ListFriends_Call) RunAndReturn(run func(context.Context, int64) ([]repo.User, error)) *FriendshipRepoMock_ListFriends_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingRequests provides a mock function with given fields: ctx, userID
func (_m *FriendshipRepoMock) ListPendingRequests(ctx context.Context, userID int64) ([]repo.PendingRequest, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingRequests")
	}

	var r0 []repo.PendingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]repo.PendingRequest, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []repo.PendingRequest); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.PendingRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendshipRepoMock_ListPendingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingRequests'
type FriendshipRepoMock_ListPendingRequests_Call struct {
	*mock.Call
}

// ListPendingRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *FriendshipRepoMock_Expecter) ListPendingRequests(ctx interface{}, userID interface{}) *FriendshipRepoMock_ListPendingRequests_Call {
	return &FriendshipRepoMock_ListPendingRequests_Call{Call: _e.mock.On("ListPendingRequests", ctx, userID)}
}

func (_c *FriendshipRepoMock_ListPendingRequests_Call) Run(run func(ctx context.Context, userID int64)) *FriendshipRepoMock_ListPendingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FriendshipRepoMock_ListPendingRequests_Call) Return(_a0 []repo.PendingRequest, _a1 error) *FriendshipRepoMock_ListPendingRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendshipRepoMock_ListPendingRequests_Call) RunAndReturn(run func(context.Context, int64) ([]repo.PendingRequest, error)) *FriendshipRepoMock_ListPendingRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RejectRequest provides a mock function with given fields: ctx, friendshipID, userID
func (_m *FriendshipRepoMock) RejectRequest(ctx context.Context, friendshipID int64, userID int64) error {
	ret := _m.Called(ctx, friendshipID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RejectRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, friendshipID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendshipRepoMock_RejectRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectRequest'
type FriendshipRepoMock_RejectRequest_Call struct {
	*mock.Call
}

// RejectRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - friendshipID int64
//   - userID int64
func (_e *FriendshipRepoMock_Expecter) RejectRequest(ctx interface{}, friendshipID interface{}, userID interface{}) *FriendshipRepoMock_RejectRequest_Call {
	return &FriendshipRepoMock_RejectRequest_Call{Call: _e.mock.On("RejectRequest", ctx, friendshipID, userID)}
}

func (_c *FriendshipRepoMock_RejectRequest_Call) Run(run func(ctx context.Context, friendshipID int64, userID int64)) *FriendshipRepoMock_RejectRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendshipRepoMock_RejectRequest_Call) Return(_a0 error) *FriendshipRepoMock_RejectRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FriendshipRepoMock_RejectRequest_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FriendshipRepoMock_RejectRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SendRequest provides a mock function with given fields: ctx, requesterID, addresseeID
func (_m *FriendshipRepoMock) SendRequest(ctx context.Context, requesterID int64, addresseeID int64) error {
	ret := _m.Called(ctx, requesterID, addresseeID)

	if len(ret) == 0 {
		panic("no return value specified for SendRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, requesterID, addresseeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendshipRepoMock_SendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRequest'
type FriendshipRepoMock_SendRequest_Call struct {
	*mock.Call
}

// SendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID int64
//   - addresseeID int64
func (_e *FriendshipRepoMock_Expecter) SendRequest(ctx interface{}, requesterID interface{}, addresseeID interface{}) *FriendshipRepoMock_SendRequest_Call {
	return &FriendshipRepoMock_SendRequest_Call{Call: _e.mock.On("SendRequest", ctx, requesterID, addresseeID)}
}

func (_c *FriendshipRepoMock_SendRequest_Call) Run(run func(ctx context.Context, requesterID int64, addresseeID int64)) *FriendshipRepoMock_SendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendshipRepoMock_SendRequest_Call) Return(_a0 error) *FriendshipRepoMock_SendRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FriendshipRepoMock_SendRequest_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FriendshipRepoMock_SendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendshipRepoMock creates a new instance of FriendshipRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendshipRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendshipRepoMock {
	mock := &FriendshipRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
