// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// MessageRepoMock is an autogenerated mock type for the MessageRepo type
type MessageRepoMock struct {
	mock.Mock
}

type MessageRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageRepoMock) EXPECT() *MessageRepoMock_Expecter {
	return &MessageRepoMock_Expecter{mock: &_m.Mock}
}

// FetchAfter provides a mock function with given fields: ctx, channelID, afterSeq, limit
func (_m *MessageRepoMock) FetchAfter(ctx context.Context, channelID int64, afterSeq int64, limit int) ([]repo.Message, error) {
	ret := _m.Called(ctx, channelID, afterSeq, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchAfter")
	}

	var r0 []repo.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) ([]repo.Message, error)); ok {
		return rf(ctx, channelID, afterSeq, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) []repo.Message); ok {
		r0 = rf(ctx, channelID, afterSeq, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int) error); ok {
		r1 = rf(ctx, channelID, afterSeq, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepoMock_FetchAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAfter'
type MessageRepoMock_FetchAfter_Call struct {
	*mock.Call
}

// FetchAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - afterSeq int64
//   - limit int
func (_e *MessageRepoMock_Expecter) FetchAfter(ctx interface{}, channelID interface{}, afterSeq interface{}, limit interface{}) *MessageRepoMock_FetchAfter_Call {
	return &MessageRepoMock_FetchAfter_Call{Call: _e.mock.On("FetchAfter", ctx, channelID, afterSeq, limit)}
}

func (_c *MessageRepoMock_FetchAfter_Call) Run(run func(ctx context.Context, channelID int64, afterSeq int64, limit int)) *MessageRepoMock_FetchAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *MessageRepoMock_FetchAfter_Call) Return(_a0 []repo.Message, _a1 error) *MessageRepoMock_FetchAfter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepoMock_FetchAfter_Call) RunAndReturn(run func(context.Context, int64, int64, int) ([]repo.Message, error)) *MessageRepoMock_FetchAfter_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAround provides a mock function with given fields: ctx, channelID, userID, aroundSeq, limit
func (_m *MessageRepoMock) FetchAround(ctx context.Context, channelID int64, userID int64, aroundSeq int64, limit int) ([]repo.Message, error) {
	ret := _m.Called(ctx, channelID, userID, aroundSeq, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchAround")
	}

	var r0 []repo.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, int) ([]repo.Message, error)); ok {
		return rf(ctx, channelID, userID, aroundSeq, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, int) []repo.Message); ok {
		r0 = rf(ctx, channelID, userID, aroundSeq, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64, int) error); ok {
		r1 = rf(ctx, channelID, userID, aroundSeq, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepoMock_FetchAround_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAround'
type MessageRepoMock_FetchAround_Call struct {
	*mock.Call
}

// FetchAround is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - userID int64
//   - aroundSeq int64
//   - limit int
func (_e *MessageRepoMock_Expecter) FetchAround(ctx interface{}, channelID interface{}, userID interface{}, aroundSeq interface{}, limit interface{}) *MessageRepoMock_FetchAround_Call {
	return &MessageRepoMock_FetchAround_Call{Call: _e.mock.On("FetchAround", ctx, channelID, userID, aroundSeq, limit)}
}

func (_c *MessageRepoMock_FetchAround_Call) Run(run func(ctx context.Context, channelID int64, userID int64, aroundSeq int64, limit int)) *MessageRepoMock_FetchAround_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64), args[4].(int))
	})
	return _c
}

func (_c *MessageRepoMock_FetchAround_Call) Return(_a0 []repo.Message, _a1 error) *MessageRepoMock_FetchAround_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepoMock_FetchAround_Call) RunAndReturn(run func(context.Context, int64, int64, int64, int) ([]repo.Message, error)) *MessageRepoMock_FetchAround_Call {
	_c.Call.Return(run)
	return _c
}

// FetchBefore provides a mock function with given fields: ctx, channelID, userID, beforeSeq, limit
func (_m *MessageRepoMock) FetchBefore(ctx context.Context, channelID int64, userID int64, beforeSeq int64, limit int) ([]repo.Message, error) {
	ret := _m.Called(ctx, channelID, userID, beforeSeq, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchBefore")
	}

	var r0 []repo.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, int) ([]repo.Message, error)); ok {
		return rf(ctx, channelID, userID, beforeSeq, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, int) []repo.Message); ok {
		r0 = rf(ctx, channelID, userID, beforeSeq, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64, int) error); ok {
		r1 = rf(ctx, channelID, userID, beforeSeq, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepoMock_FetchBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBefore'
type MessageRepoMock_FetchBefore_Call struct {
	*mock.Call
}

// FetchBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - userID int64
//   - beforeSeq int64
//   - limit int
func (_e *MessageRepoMock_Expecter) FetchBefore(ctx interface{}, channelID interface{}, userID interface{}, beforeSeq interface{}, limit interface{}) *MessageRepoMock_FetchBefore_Call {
	return &MessageRepoMock_FetchBefore_Call{Call: _e.mock.On("FetchBefore", ctx, channelID, userID, beforeSeq, limit)}
}

func (_c *MessageRepoMock_FetchBefore_Call) Run(run func(ctx context.Context, channelID int64, userID int64, beforeSeq int64, limit int)) *MessageRepoMock_FetchBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64), args[4].(int))
	})
	return _c
}

func (_c *MessageRepoMock_FetchBefore_Call) Return(_a0 []repo.Message, _a1 error) *MessageRepoMock_FetchBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepoMock_FetchBefore_Call) RunAndReturn(run func(context.Context, int64, int64, int64, int) ([]repo.Message, error)) *MessageRepoMock_FetchBefore_Call {
	_c.Call.Return(run)
	return _c
}

// FetchForUser provides a mock function with given fields: ctx, channelID, userID, afterSeq, limit
func (_m *MessageRepoMock) FetchForUser(ctx context.Context, channelID int64, userID int64, afterSeq int64, limit int) ([]repo.Message, error) {
	ret := _m.Called(ctx, channelID, userID, afterSeq, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchForUser")
	}

	var r0 []repo.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, int) ([]repo.Message, error)); ok {
		return rf(ctx, channelID, userID, afterSeq, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, int) []repo.Message); ok {
		r0 = rf(ctx, channelID, userID, afterSeq, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64, int) error); ok {
		r1 = rf(ctx, channelID, userID, afterSeq, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepoMock_FetchForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchForUser'
type MessageRepoMock_FetchForUser_Call struct {
	*mock.Call
}

// FetchForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID int64
//   - userID int64
//   - afterSeq int64
//   - limit int
func (_e *MessageRepoMock_Expecter) FetchForUser(ctx interface{}, channelID interface{}, userID interface{}, afterSeq interface{}, limit interface{}) *MessageRepoMock_FetchForUser_Call {
	return &MessageRepoMock_FetchForUser_Call{Call: _e.mock.On("FetchForUser", ctx, channelID, userID, afterSeq, limit)}
}

func (_c *MessageRepoMock_FetchForUser_Call) Run(run func(ctx context.Context, channelID int64, userID int64, afterSeq int64, limit int)) *MessageRepoMock_FetchForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64), args[4].(int))
	})
	return _c
}

func (_c *MessageRepoMock_FetchForUser_Call) Return(_a0 []repo.Message, _a1 error) *MessageRepoMock_FetchForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepoMock_FetchForUser_Call) RunAndReturn(run func(context.Context, int64, int64, int64, int) ([]repo.Message, error)) *MessageRepoMock_FetchForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MessageRepoMock) GetByID(ctx context.Context, id int64) (*repo.Message, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *repo.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repo.Message, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repo.Message); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepoMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MessageRepoMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MessageRepoMock_Expecter) GetByID(ctx interface{}, id interface{}) *MessageRepoMock_GetByID_Call {
	return &MessageRepoMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MessageRepoMock_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MessageRepoMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MessageRepoMock_GetByID_Call) Return(_a0 *repo.Message, _a1 error) *MessageRepoMock_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepoMock_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*repo.Message, error)) *MessageRepoMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, msg
func (_m *MessageRepoMock) Send(ctx context.Context, msg *repo.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageRepoMock_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MessageRepoMock_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *repo.Message
func (_e *MessageRepoMock_Expecter) Send(ctx interface{}, msg interface{}) *MessageRepoMock_Send_Call {
	return &MessageRepoMock_Send_Call{Call: _e.mock.On("Send", ctx, msg)}
}

func (_c *MessageRepoMock_Send_Call) Run(run func(ctx context.Context, msg *repo.Message)) *MessageRepoMock_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repo.Message))
	})
	return _c
}

func (_c *MessageRepoMock_Send_Call) Return(_a0 error) *MessageRepoMock_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageRepoMock_Send_Call) RunAndReturn(run func(context.Context, *repo.Message) error) *MessageRepoMock_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageRepoMock creates a new instance of MessageRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageRepoMock {
	mock := &MessageRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
