// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// SearchRepoMock is an autogenerated mock type for the SearchRepo type
type SearchRepoMock struct {
	mock.Mock
}

type SearchRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SearchRepoMock) EXPECT() *SearchRepoMock_Expecter {
	return &SearchRepoMock_Expecter{mock: &_m.Mock}
}

// SearchChannels provides a mock function with given fields: ctx, q, callerID, limit
func (_m *SearchRepoMock) SearchChannels(ctx context.Context, q string, callerID int64, limit int) ([]repo.Channel, error) {
	ret := _m.Called(ctx, q, callerID, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchChannels")
	}

	var r0 []repo.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) ([]repo.Channel, error)); ok {
		return rf(ctx, q, callerID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) []repo.Channel); ok {
		r0 = rf(ctx, q, callerID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int) error); ok {
		r1 = rf(ctx, q, callerID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRepoMock_SearchChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchChannels'
type SearchRepoMock_SearchChannels_Call struct {
	*mock.Call
}

// SearchChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - q string
//   - callerID int64
//   - limit int
func (_e *SearchRepoMock_Expecter) SearchChannels(ctx interface{}, q interface{}, callerID interface{}, limit interface{}) *SearchRepoMock_SearchChannels_Call {
	return &SearchRepoMock_SearchChannels_Call{Call: _e.mock.On("SearchChannels", ctx, q, callerID, limit)}
}

func (_c *SearchRepoMock_SearchChannels_Call) Run(run func(ctx context.Context, q string, callerID int64, limit int)) *SearchRepoMock_SearchChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *SearchRepoMock_SearchChannels_Call) Return(_a0 []repo.Channel, _a1 error) *SearchRepoMock_SearchChannels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchRepoMock_SearchChannels_Call) RunAndReturn(run func(context.Context, string, int64, int) ([]repo.Channel, error)) *SearchRepoMock_SearchChannels_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMessages provides a mock function with given fields: ctx, q, userID, channelID, limit
func (_m *SearchRepoMock) SearchMessages(ctx context.Context, q string, userID int64, channelID int64, limit int) ([]repo.MessageSearchResult, error) {
	ret := _m.Called(ctx, q, userID, channelID, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchMessages")
	}

	var r0 []repo.MessageSearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int) ([]repo.MessageSearchResult, error)); ok {
		return rf(ctx, q, userID, channelID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int) []repo.MessageSearchResult); ok {
		r0 = rf(ctx, q, userID, channelID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.MessageSearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, int) error); ok {
		r1 = rf(ctx, q, userID, channelID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRepoMock_SearchMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMessages'
type SearchRepoMock_SearchMessages_Call struct {
	*mock.Call
}

// SearchMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - q string
//   - userID int64
//   - channelID int64
//   - limit int
func (_e *SearchRepoMock_Expecter) SearchMessages(ctx interface{}, q interface{}, userID interface{}, channelID interface{}, limit interface{}) *SearchRepoMock_SearchMessages_Call {
	return &SearchRepoMock_SearchMessages_Call{Call: _e.mock.On("SearchMessages", ctx, q, userID, channelID, limit)}
}

func (_c *SearchRepoMock_SearchMessages_Call) Run(run func(ctx context.Context, q string, userID int64, channelID int64, limit int)) *SearchRepoMock_SearchMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(int))
	})
	return _c
}

func (_c *SearchRepoMock_SearchMessages_Call) Return(_a0 []repo.MessageSearchResult, _a1 error) *SearchRepoMock_SearchMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchRepoMock_SearchMessages_Call) RunAndReturn(run func(context.Context, string, int64, int64, int) ([]repo.MessageSearchResult, error)) *SearchRepoMock_SearchMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, q, callerID, limit
func (_m *SearchRepoMock) SearchUsers(ctx context.Context, q string, callerID int64, limit int) ([]repo.User, error) {
	ret := _m.Called(ctx, q, callerID, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) ([]repo.User, error)); ok {
		return rf(ctx, q, callerID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) []repo.User); ok {
		r0 = rf(ctx, q, callerID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int) error); ok {
		r1 = rf(ctx, q, callerID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRepoMock_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type SearchRepoMock_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - q string
//   - callerID int64
//   - limit int
func (_e *SearchRepoMock_Expecter) SearchUsers(ctx interface{}, q interface{}, callerID interface{}, limit interface{}) *SearchRepoMock_SearchUsers_Call {
	return &SearchRepoMock_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, q, callerID, limit)}
}

func (_c *SearchRepoMock_SearchUsers_Call) Run(run func(ctx context.Context, q string, callerID int64, limit int)) *SearchRepoMock_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *SearchRepoMock_SearchUsers_Call) Return(_a0 []repo.User, _a1 error) *SearchRepoMock_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchRepoMock_SearchUsers_Call) RunAndReturn(run func(context.Context, string, int64, int) ([]repo.User, error)) *SearchRepoMock_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewSearchRepoMock creates a new instance of SearchRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchRepoMock {
	mock := &SearchRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
