// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// UserSettingsRepoMock is an autogenerated mock type for the UserSettingsRepo type
type UserSettingsRepoMock struct {
	mock.Mock
}

type UserSettingsRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSettingsRepoMock) EXPECT() *UserSettingsRepoMock_Expecter {
	return &UserSettingsRepoMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID
func (_m *UserSettingsRepoMock) Get(ctx context.Context, userID int64) (*repo.UserSettings, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repo.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repo.UserSettings, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repo.UserSettings); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSettingsRepoMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserSettingsRepoMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *UserSettingsRepoMock_Expecter) Get(ctx interface{}, userID interface{}) *UserSettingsRepoMock_Get_Call {
	return &UserSettingsRepoMock_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *UserSettingsRepoMock_Get_Call) Run(run func(ctx context.Context, userID int64)) *UserSettingsRepoMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserSettingsRepoMock_Get_Call) Return(_a0 *repo.UserSettings, _a1 error) *UserSettingsRepoMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserSettingsRepoMock_Get_Call) RunAndReturn(run func(context.Context, int64) (*repo.UserSettings, error)) *UserSettingsRepoMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, s
func (_m *UserSettingsRepoMock) Upsert(ctx context.Context, s *repo.UserSettings) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.UserSettings) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserSettingsRepoMock_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type UserSettingsRepoMock_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - s *repo.UserSettings
func (_e *UserSettingsRepoMock_Expecter) Upsert(ctx interface{}, s interface{}) *UserSettingsRepoMock_Upsert_Call {
	return &UserSettingsRepoMock_Upsert_Call{Call: _e.mock.On("Upsert", ctx, s)}
}

func (_c *UserSettingsRepoMock_Upsert_Call) Run(run func(ctx context.Context, s *repo.UserSettings)) *UserSettingsRepoMock_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repo.UserSettings))
	})
	return _c
}

func (_c *UserSettingsRepoMock_Upsert_Call) Return(_a0 error) *UserSettingsRepoMock_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserSettingsRepoMock_Upsert_Call) RunAndReturn(run func(context.Context, *repo.UserSettings) error) *UserSettingsRepoMock_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserSettingsRepoMock creates a new instance of UserSettingsRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSettingsRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSettingsRepoMock {
	mock := &UserSettingsRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
