// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "im-server/internal/repo"

	mock "github.com/stretchr/testify/mock"
)

// UserRepoMock is an autogenerated mock type for the UserRepo type
type UserRepoMock struct {
	mock.Mock
}

type UserRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepoMock) EXPECT() *UserRepoMock_Expecter {
	return &UserRepoMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, u
func (_m *UserRepoMock) Create(ctx context.Context, u *repo.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepoMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepoMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *repo.User
func (_e *UserRepoMock_Expecter) Create(ctx interface{}, u interface{}) *UserRepoMock_Create_Call {
	return &UserRepoMock_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *UserRepoMock_Create_Call) Run(run func(ctx context.Context, u *repo.User)) *UserRepoMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repo.User))
	})
	return _c
}

func (_c *UserRepoMock_Create_Call) Return(_a0 error) *UserRepoMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepoMock_Create_Call) RunAndReturn(run func(context.Context, *repo.User) error) *UserRepoMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepoMock) GetByEmail(ctx context.Context, email string) (*repo.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*repo.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *repo.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepoMock_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepoMock_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepoMock_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepoMock_GetByEmail_Call {
	return &UserRepoMock_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepoMock_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepoMock_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepoMock_GetByEmail_Call) Return(_a0 *repo.User, _a1 error) *UserRepoMock_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepoMock_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*repo.User, error)) *UserRepoMock_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepoMock) GetByID(ctx context.Context, id int64) (*repo.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repo.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repo.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepoMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepoMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserRepoMock_Expecter) GetByID(ctx interface{}, id interface{}) *UserRepoMock_GetByID_Call {
	return &UserRepoMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserRepoMock_GetByID_Call) Run(run func(ctx context.Context, id int64)) *UserRepoMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserRepoMock_GetByID_Call) Return(_a0 *repo.User, _a1 error) *UserRepoMock_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepoMock_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*repo.User, error)) *UserRepoMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepoMock) GetByUsername(ctx context.Context, username string) (*repo.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*repo.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *repo.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepoMock_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type UserRepoMock_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserRepoMock_Expecter) GetByUsername(ctx interface{}, username interface{}) *UserRepoMock_GetByUsername_Call {
	return &UserRepoMock_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *UserRepoMock_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *UserRepoMock_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepoMock_GetByUsername_Call) Return(_a0 *repo.User, _a1 error) *UserRepoMock_GetByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepoMock_GetByUsername_Call) RunAndReturn(run func(context.Context, string) (*repo.User, error)) *UserRepoMock_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, callerID
func (_m *UserRepoMock) Search(ctx context.Context, query string, callerID int64) ([]repo.User, error) {
	ret := _m.Called(ctx, query, callerID)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]repo.User, error)); ok {
		return rf(ctx, query, callerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []repo.User); ok {
		r0 = rf(ctx, query, callerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, query, callerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepoMock_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type UserRepoMock_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - callerID int64
func (_e *UserRepoMock_Expecter) Search(ctx interface{}, query interface{}, callerID interface{}) *UserRepoMock_Search_Call {
	return &UserRepoMock_Search_Call{Call: _e.mock.On("Search", ctx, query, callerID)}
}

func (_c *UserRepoMock_Search_Call) Run(run func(ctx context.Context, query string, callerID int64)) *UserRepoMock_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *UserRepoMock_Search_Call) Return(_a0 []repo.User, _a1 error) *UserRepoMock_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepoMock_Search_Call) RunAndReturn(run func(context.Context, string, int64) ([]repo.User, error)) *UserRepoMock_Search_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, displayName, avatarURL
func (_m *UserRepoMock) UpdateProfile(ctx context.Context, userID int64, displayName string, avatarURL string) (*repo.User, error) {
	ret := _m.Called(ctx, userID, displayName, avatarURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (*repo.User, error)); ok {
		return rf(ctx, userID, displayName, avatarURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) *repo.User); ok {
		r0 = rf(ctx, userID, displayName, avatarURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, userID, displayName, avatarURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepoMock_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserRepoMock_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - displayName string
//   - avatarURL string
func (_e *UserRepoMock_Expecter) UpdateProfile(ctx interface{}, userID interface{}, displayName interface{}, avatarURL interface{}) *UserRepoMock_UpdateProfile_Call {
	return &UserRepoMock_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, displayName, avatarURL)}
}

func (_c *UserRepoMock_UpdateProfile_Call) Run(run func(ctx context.Context, userID int64, displayName string, avatarURL string)) *UserRepoMock_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserRepoMock_UpdateProfile_Call) Return(_a0 *repo.User, _a1 error) *UserRepoMock_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepoMock_UpdateProfile_Call) RunAndReturn(run func(context.Context, int64, string, string) (*repo.User, error)) *UserRepoMock_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepoMock creates a new instance of UserRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepoMock {
	mock := &UserRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
