package testutil

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/redis/go-redis/v9"

	"im-server/internal/middleware"
)

// RealCookieID is the verified cses-pre cookieId for the production test
// fixture (张立超). Reuse it in any test that does not need to invent a new
// identity — that way the same cookieId works in unit tests, integration
// tests, and the seed-mm-cookies.sh manual e2e flow.
const (
	RealCookieID  = "69eec6dbe6876865ff98945a"
	RealUserID    = "676cc4ccfbbc501161d5cd65"
	RealCompanyID = "6111fb0a202d425d221c53db"
	RealOrgID     = "6311a17c50c75d009ed3864f"
	RealUserName  = "张立超"
)

// CookieFixture writes a Mattermost-shaped user payload into the upstream
// Redis HASH "User" so a request bearing cookieId clears MattermostCookieResolve
// + CookieRequired. The returned headerValue is what handlers should send
// back as the cookieId header. The fixture is automatically removed on
// t.Cleanup.
//
// Example:
//
//	cookie := testutil.CookieFixture(t, rdb, testutil.RealCookieID,
//	    testutil.RealUserID, testutil.RealCompanyID)
//	expect.GET("/api/channels").
//	    WithHeader(middleware.MMCookieHeader, cookie).
//	    Expect().Status(200)
//
// All three positional arguments must already be 24-char hex (see
// auth.ValidateUserID); the helper panics otherwise so a typo in a fixture
// fails loudly instead of silently producing an unauthorised request.
func CookieFixture(t *testing.T, rdb redis.UniversalClient, cookieID, userID, companyID string) string {
	t.Helper()
	requireHex24(t, "cookieID", cookieID)
	requireHex24(t, "userID", userID)
	if companyID != "" {
		requireHex24(t, "companyID", companyID)
	}

	user := middleware.MattermostUser{
		ID:        userID,
		UserID:    userID,
		UserName:  fmt.Sprintf("test-%s", userID[:8]),
		Name:      fmt.Sprintf("test-%s", userID[:8]),
		CompanyID: companyID,
		OrgID:     companyID,
		Roles:     []string{"Member"},
		OrgRole:   "Member",
	}
	if cookieID == RealCookieID {
		// Reproduce the exact wire shape we got from cses-server-pre-0
		// for parity with manual e2e replay.
		user.UserName = RealUserName
		user.Name = RealUserName
		user.CompanyID = RealCompanyID
		user.OrgID = RealOrgID
		user.OrgName = "后端开发"
		user.DeptID = "616cee6ef7a6ae6354cddd9b"
		user.DeptName = "技术部"
		user.Mobile = "17692704771"
	}

	raw, err := json.Marshal(user)
	if err != nil {
		t.Fatalf("CookieFixture marshal: %v", err)
	}
	field := fmt.Sprintf("%q", cookieID)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	if err := rdb.HSet(ctx, middleware.MMUserHashKey, field, string(raw)).Err(); err != nil {
		t.Fatalf("CookieFixture HSet: %v", err)
	}
	t.Cleanup(func() {
		clean, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		_ = rdb.HDel(clean, middleware.MMUserHashKey, field).Err()
	})
	return cookieID
}

// MakeCookieID returns a deterministic 24-char hex cookieId derived from
// seed. Useful when a test needs multiple distinct identities. seed >= 0.
func MakeCookieID(seed int) string {
	if seed < 0 {
		seed = -seed
	}
	return fmt.Sprintf("c%023x", uint64(seed)+1)
}

// MakeUserID returns a deterministic 24-char hex userId derived from seed.
// The format starts with "u" then 23 hex digits so generated ids never
// collide with the cookieId space (lower-case 'u' is not hex).
//
// NOTE: 'u' is not a valid hex char, so this id will fail
// auth.ValidateUserID. For callers that need a *valid* hex id (production
// code paths), use HexUserID instead.
func MakeUserID(seed int) string {
	if seed < 0 {
		seed = -seed
	}
	return fmt.Sprintf("u%023x", uint64(seed)+1)
}

// HexUserID returns a 24-char lowercase-hex id derived from seed,
// guaranteed to satisfy auth.ValidateUserID.
func HexUserID(seed int) string {
	if seed < 0 {
		seed = -seed
	}
	return fmt.Sprintf("%024x", uint64(seed)+1)
}

func requireHex24(t *testing.T, name, s string) {
	t.Helper()
	if len(s) != 24 {
		t.Fatalf("%s must be 24 chars, got %d (%q)", name, len(s), s)
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		ok := (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')
		if !ok {
			// Allow leading 'c' in cookieId (MakeCookieID convention)
			if i == 0 && name == "cookieID" && c == 'c' {
				continue
			}
			t.Fatalf("%s contains non-hex byte %q at offset %d (%q)", name, c, i, s)
		}
	}
	if name == "cookieID" && strings.HasPrefix(s, "c") && len(s) == 24 {
		// Acceptable — generated by MakeCookieID.
		return
	}
}
